const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('vaultApi', {
  getState: () => ipcRenderer.invoke('vault:getState'),
  register: (payload) => ipcRenderer.invoke('vault:register', payload),
  loginLocal: (payload) => ipcRenderer.invoke('vault:loginLocal', payload),
  logoutLocal: () => ipcRenderer.invoke('vault:logoutLocal'),
  updateRecovery: (payload) => ipcRenderer.invoke('vault:updateRecovery', payload),
  changeLocalPassword: (payload) => ipcRenderer.invoke('vault:changeLocalPassword', payload),
  resetPassword: (payload) => ipcRenderer.invoke('vault:resetPassword', payload),
  saveSettings: (settings) => ipcRenderer.invoke('vault:saveSettings', settings),
  saveLocalVectorSettings: (payload) => ipcRenderer.invoke('vault:saveLocalVectorSettings', payload),
  testFeishuSync: (payload) => ipcRenderer.invoke('vault:testFeishuSync', payload),
  login: () => ipcRenderer.invoke('vault:login'),
  loginFeishu: () => ipcRenderer.invoke('vault:loginFeishu'),
  openFeishuRedirectSettings: () => ipcRenderer.invoke('vault:openFeishuRedirectSettings'),
  logout: () => ipcRenderer.invoke('vault:logout'),
  chooseFiles: () => ipcRenderer.invoke('vault:chooseFiles'),
  chooseDirectory: () => ipcRenderer.invoke('vault:chooseDirectory'),
  scanWechatAttachments: () => ipcRenderer.invoke('vault:scanWechatAttachments'),
  chooseWechatAttachments: () => ipcRenderer.invoke('vault:chooseWechatAttachments'),
  uploadFiles: (payload) => ipcRenderer.invoke('vault:uploadFiles', payload),
  onUploadProgress: (callback) => {
    if (typeof callback !== 'function') return () => {};
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('vault:uploadProgress', listener);
    return () => ipcRenderer.removeListener('vault:uploadProgress', listener);
  },
  uploadText: (payload) => ipcRenderer.invoke('vault:uploadText', payload),
  downloadRecord: (payload) => ipcRenderer.invoke('vault:downloadRecord', payload),
  openAsset: (payload) => ipcRenderer.invoke('vault:openAsset', payload),
  unlockItem: (payload) => ipcRenderer.invoke('vault:unlockItem', payload),
  openItem: (payload) => ipcRenderer.invoke('vault:openItem', payload),
  saveItemFile: (payload) => ipcRenderer.invoke('vault:saveItemFile', payload),
  forgetRecord: (recordId) => ipcRenderer.invoke('vault:forgetRecord', recordId),
  forgetItem: (itemId) => ipcRenderer.invoke('vault:forgetItem', itemId),
  createLibraryItem: (payload) => ipcRenderer.invoke('vault:createLibraryItem', payload),
  saveAiProfile: (payload) => ipcRenderer.invoke('vault:saveAiProfile', payload),
  listModels: (payload) => ipcRenderer.invoke('vault:listModels', payload),
  testModel: (payload) => ipcRenderer.invoke('vault:testModel', payload),
  saveKnowledgeSources: (payload) => ipcRenderer.invoke('vault:saveKnowledgeSources', payload),
  saveVectorSources: (payload) => ipcRenderer.invoke('vault:saveVectorSources', payload),
  saveObsidianSources: (payload) => ipcRenderer.invoke('vault:saveObsidianSources', payload),
  saveFeishuWikiSettings: (payload) => ipcRenderer.invoke('vault:saveFeishuWikiSettings', payload),
  queryKnowledgeCenter: (payload) => ipcRenderer.invoke('vault:queryKnowledgeCenter', payload),
  saveProjectAccount: (payload) => ipcRenderer.invoke('vault:saveProjectAccount', payload),
  saveProjectRepository: (payload) => ipcRenderer.invoke('vault:saveProjectRepository', payload),
  getProjectsDetail: () => ipcRenderer.invoke('vault:getProjectsDetail'),
  deleteProjectRepository: (repoId) => ipcRenderer.invoke('vault:deleteProjectRepository', repoId),
  runProjectAction: (payload) => ipcRenderer.invoke('vault:runProjectAction', payload),
  setContext: (payload) => ipcRenderer.invoke('vault:setContext', payload),
  createGroup: (payload) => ipcRenderer.invoke('vault:createGroup', payload),
  inviteToGroup: (payload) => ipcRenderer.invoke('vault:inviteToGroup', payload),
  leaveGroup: (groupId) => ipcRenderer.invoke('vault:leaveGroup', groupId),
  listGroupMembers: (groupId) => ipcRenderer.invoke('vault:listGroupMembers', groupId),
  search: (payload) => ipcRenderer.invoke('vault:search', payload),
  reindexSearch: () => ipcRenderer.invoke('vault:reindexSearch'),
  copyItemToGroup: (payload) => ipcRenderer.invoke('vault:copyItemToGroup', payload),
  syncManifest: (payload) => ipcRenderer.invoke('vault:syncManifest', payload),
  pullManifest: (payload) => ipcRenderer.invoke('vault:pullManifest', payload),
  fullSync: (payload) => ipcRenderer.invoke('vault:fullSync', payload),
  removeGroupMember: (payload) => ipcRenderer.invoke('vault:removeGroupMember', payload),
  rotateGroupKey: (groupId) => ipcRenderer.invoke('vault:rotateGroupKey', groupId),
  updateMemberRole: (payload) => ipcRenderer.invoke('vault:updateMemberRole', payload),
  transferGroupOwnership: (payload) => ipcRenderer.invoke('vault:transferGroupOwnership', payload),
  acceptPendingInvites: () => ipcRenderer.invoke('vault:acceptPendingInvites'),
  openExternal: (url) => ipcRenderer.invoke('vault:openExternal', url),
  showDatabase: () => ipcRenderer.invoke('vault:showDatabase'),
});
