const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('vaultApi', {
  getState: () => ipcRenderer.invoke('vault:getState'),
  register: (payload) => ipcRenderer.invoke('vault:register', payload),
  loginLocal: (payload) => ipcRenderer.invoke('vault:loginLocal', payload),
  logoutLocal: () => ipcRenderer.invoke('vault:logoutLocal'),
  updateRecovery: (payload) => ipcRenderer.invoke('vault:updateRecovery', payload),
  resetPassword: (payload) => ipcRenderer.invoke('vault:resetPassword', payload),
  saveSettings: (settings) => ipcRenderer.invoke('vault:saveSettings', settings),
  login: () => ipcRenderer.invoke('vault:login'),
  logout: () => ipcRenderer.invoke('vault:logout'),
  chooseFiles: () => ipcRenderer.invoke('vault:chooseFiles'),
  chooseDirectory: () => ipcRenderer.invoke('vault:chooseDirectory'),
  uploadFiles: (payload) => ipcRenderer.invoke('vault:uploadFiles', payload),
  uploadText: (payload) => ipcRenderer.invoke('vault:uploadText', payload),
  downloadRecord: (payload) => ipcRenderer.invoke('vault:downloadRecord', payload),
  unlockItem: (payload) => ipcRenderer.invoke('vault:unlockItem', payload),
  saveItemFile: (payload) => ipcRenderer.invoke('vault:saveItemFile', payload),
  forgetRecord: (recordId) => ipcRenderer.invoke('vault:forgetRecord', recordId),
  forgetItem: (itemId) => ipcRenderer.invoke('vault:forgetItem', itemId),
  createLibraryItem: (payload) => ipcRenderer.invoke('vault:createLibraryItem', payload),
  saveAiProfile: (payload) => ipcRenderer.invoke('vault:saveAiProfile', payload),
  saveKnowledgeSources: (payload) => ipcRenderer.invoke('vault:saveKnowledgeSources', payload),
  saveVectorSources: (payload) => ipcRenderer.invoke('vault:saveVectorSources', payload),
  saveObsidianSources: (payload) => ipcRenderer.invoke('vault:saveObsidianSources', payload),
  queryKnowledgeCenter: (payload) => ipcRenderer.invoke('vault:queryKnowledgeCenter', payload),
  saveProjectAccount: (payload) => ipcRenderer.invoke('vault:saveProjectAccount', payload),
  saveProjectRepository: (payload) => ipcRenderer.invoke('vault:saveProjectRepository', payload),
  deleteProjectRepository: (repoId) => ipcRenderer.invoke('vault:deleteProjectRepository', repoId),
  runProjectAction: (payload) => ipcRenderer.invoke('vault:runProjectAction', payload),
  openExternal: (url) => ipcRenderer.invoke('vault:openExternal', url),
  showDatabase: () => ipcRenderer.invoke('vault:showDatabase'),
});
